services:
  - type: web
    name: energymonitor
    env: php
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://energymonitor.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: energymonitor_db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: energymonitor_db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: energymonitor_db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: energymonitor_db
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: energymonitor_db
          property: password
      - key: APP_KEY
        generateValue: true 